#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch bar
polybar bar --config=/home/chew/Documents/8_Config/2_polybar/config_bottom
