#!/bin/bash

export TERMINAL="xfce4-terminal"

export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export LIBSEAT_BACKEND=logind

# Added SDL_VIDEODRIVER=wayland, _JAVA_AWT_WM_NONREPARENTING=1, XDG_SESSION_DESKTOP=sway for
# flameshot
export _JAVA_AWT_WM_NONREPARENTING=1 # For MATLAB too
export SDL_VIDEODRIVER=wayland
#export XDG_SESSION_DESKTOP=sway

sway
